### ISSUE TITLE
Items not appearing in the proximity list

### ISSUE THREAD

**Issue by pvm** [mxswat/pz-ProximityInventory#2]
Not sure how this "Mod Manager" works for dedicated servers (shouldn't be required for this) I didn't add those 2 mods because in their description they mention to not add at all.

So, I added the workshopId and the mod ids (both, with the zombyonly) and the menu/icon is working, but the items are not appearing in the list

![image](https://user-images.githubusercontent.com/2475898/184613263-554e4daf-390c-440f-801b-d76b550dbfe9.png)

There's any other configuration that we need to do in the dedicated server for the mod to work?

**Comment by mxswat** [comment]
Do you have any other mod installed that affects loot?
Do you have any other mod that affects the inventory?
Do you get any errors in the console?

**Comment by pvm** [comment]
Yes we use these mods that might affect the inventory:
[https://steamcommunity.com/sharedfiles/filedetails/?id=2809595776](https://steamcommunity.com/sharedfiles/filedetails/?id=2809595776&searchtext=)
[https://steamcommunity.com/sharedfiles/filedetails/?id=2313387159](https://steamcommunity.com/sharedfiles/filedetails/?id=2313387159&searchtext=)

No, no log errors (in client and server) that's why is weird
Your mod is loading in the last of the mod list so should take priority right? Over the other mods?

**Comment by mxswat** [comment]
Alternative Inventory Rendering has not been tested with this mod, and at the moment I'm not interested in developing compatibility patches with this mod, I already tried to get in touch with the developer of  Alternative Inventory Rendering and he has not replied yet
