### ISSUE TITLE
Containers still highlighted if ProxInv is disabled near them

### ISSUE THREAD

**Issue by Stifling-Bossness** [mxswat/pz-ProximityInventory#3]
**Before posting**

**Do you have any other mod installed that affects loot?**
No.

**Do you have any other mod that affects the inventory?**
Yes. [Alternative Inventory Rendering](https://steamcommunity.com/sharedfiles/filedetails/?id=2809595776), [Backpack Borders](https://steamcommunity.com/sharedfiles/filedetails/?id=2808679062)

**Do you get any errors in the console?**
No.

**Steps to reproduce:**
Kill a few zombies
Walk up to them with ProxInv enabled
Toggle ProxInv while near corpses
Walk away
Still highlighted

Walking up to it and selecting the container will resume vanilla highlight behavior, so this is only a minor cosmetic issue imo.

[Video demonstration](https://youtu.be/fPGBGfLdRvk)
[Debug log](https://gist.github.com/Stifling-Bossness/6595979e3251863cdd22dcba821fbace)

**Comment by mxswat** [comment]
That's a very accurate bug report, thank you! I will look into it as soon as I'm free

**Comment by mxswat** [comment]
Fixed in today's update
