### ISSUE TITLE
Two little issues I've found that I'm not sure if they're features

### ISSUE THREAD

**Issue by S4vrk** [mxswat/pz-ProximityInventory#6]
When turning off the global container, the globe icon remains on top of other containers.
When moving, the global inventory capacity flashes between 0 and 65, it's quite bothersome.

**Do you have any other mod that affects the inventory?**
I've turned all my inventory affecting mods off, issues still persist

**Do you get any errors in the console?**
No

Image proving the globe icon issue below
![global](https://user-images.githubusercontent.com/123547824/215317773-9e52fb63-40ce-4c0b-87f2-72c0c7ac7cd2.png)

**Comment by mxswat** [comment]
Can't reproduce
